// <auto-generated />
using System;
using BitirmeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitirmeAPI.Migrations
{
    [DbContext(typeof(BitirmeAPIContext))]
    partial class BitirmeAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BitirmeAPI.Model.Comment", b =>
                {
                    b.Property<int>("commentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentID"), 1L, 1);

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("commentID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("BitirmeAPI.Model.DersProgrami", b =>
                {
                    b.Property<int>("dersProgramiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dersProgramiID"), 1L, 1);

                    b.Property<string>("carsamba1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carsamba2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carsamba3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carsamba4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carsamba5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carsamba6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuma1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuma2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuma3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuma4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuma5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuma6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pazartesi1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pazartesi2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pazartesi3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pazartesi4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pazartesi5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pazartesi6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("persembe1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("persembe2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("persembe3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("persembe4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("persembe5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("persembe6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sali1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sali2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sali3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sali4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sali5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sali6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("teacherID")
                        .HasColumnType("int");

                    b.HasKey("dersProgramiID");

                    b.ToTable("DersProgrami");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Lesson", b =>
                {
                    b.Property<int>("lessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lessonID"), 1L, 1);

                    b.Property<string>("lessonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("studentID")
                        .HasColumnType("int");

                    b.HasKey("lessonID");

                    b.HasIndex("studentID");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("BitirmeAPI.Model.LessonNote", b =>
                {
                    b.Property<int>("lessonNoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lessonNoteID"), 1L, 1);

                    b.Property<string>("beden1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("beden2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bedenDers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bedenOdev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fen1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fen2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fenDers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fenOdev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matematik1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matematik2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matematikDers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matematikOdev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resim1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resim2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resimDers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resimOdev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sosyal1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sosyal2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sosyalDers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sosyalOdev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turkce1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turkce2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turkceDers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turkceOdev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lessonNoteID");

                    b.ToTable("LessonNote");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Parent", b =>
                {
                    b.Property<int>("parentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("parentID"), 1L, 1);

                    b.Property<string>("parentMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parentPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parentSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("parentID");

                    b.ToTable("Parent");
                });

            modelBuilder.Entity("BitirmeAPI.Model.SchoolLeader", b =>
                {
                    b.Property<int>("schoolLeaderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("schoolLeaderID"), 1L, 1);

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schoolLeaderMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schoolLeaderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schoolLeaderPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schoolLeaderSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("schoolLeaderID");

                    b.ToTable("SchoolLeader");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Student", b =>
                {
                    b.Property<int>("studentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentID"), 1L, 1);

                    b.Property<string>("classCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentID");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("BitirmeAPI.Model.Teache", b =>
                {
                    b.Property<int>("teacheID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacheID"), 1L, 1);

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacheMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacheName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teachePassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacheSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("teacheID");

                    b.ToTable("Teache");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Teacher", b =>
                {
                    b.Property<int>("teacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacherID"), 1L, 1);

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacherMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacherPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacherSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("teacherID");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Lesson", b =>
                {
                    b.HasOne("BitirmeAPI.Model.Student", "Student")
                        .WithMany("Lesson")
                        .HasForeignKey("studentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Student", b =>
                {
                    b.Navigation("Lesson");
                });
#pragma warning restore 612, 618
        }
    }
}
